name: Build React App (front end)

on:
  push:
    branches:
      - featureReact
  workflow_dispatch:  # Allow manual workflow dispatches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use a valid Node.js version here

      - name: Install dependencies
        run: npm install

      - name: Set CI to false
        run: echo 'CI=false' >> $GITHUB_ENV   #used this action since react script is connsidering warning as error

      - name: Build
        run: npm run build
