name: Build React App (front end)

on:
  push:
    branches:
      - featureReact
  workflow_dispatch:  # Allow manual workflow dispatches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use a valid Node.js version here

      - name: Install dependencies
        run: npm install

      - name: Set CI to false
        run: echo 'CI=false' >> $GITHUB_ENV   #used this action since react script is connsidering warning as error

      - name: Build
        run: npm run build
        
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
         path: ~/.npm # or wherever your dependencies are stored
         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
         restore-keys: | 
          ${{ runner.os }}-node-
      - name: Static Code Analysis
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=pocalmpracrice \
            -Dsonar.projectKey=PocALmPracrice_ReactFrontEnd \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUDSECRET_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONARCLOUD_URL }}

      - name: Send notification on Slack using Webhooks - Success
        if: ${{ success() }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "React JS FrontEnd(client)project built successfully."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TOKEN }}

      - name: Send notification on Slack using Webhooks - Failure
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "React JS FrontEnd(client) build failed. Please check the build logs for details."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TOKEN }}

